name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - develop
      - main
    types:
      - completed
  workflow_dispatch:

env:
  HEROKU_API: ${{ secrets.HEROKU_API }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy staging
        uses: akhileshns/heroku-deploy@v3
        if: ${{ github.ref == 'refs/heads/development' }}
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: "elixir-gscraper"
          heroku_email: ${{ env.HEROKU_EMAIL }}

      - name: Deploy production
        uses: akhileshns/heroku-deploy@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: "elixir-gscraper"
          heroku_email: ${{ env.HEROKU_EMAIL }}
